// <auto-generated />
using BookwormAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookwormAPI.Solution.Migrations
{
    [DbContext(typeof(BookwormAPIContext))]
    partial class BookwormAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("BookwormAPI.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AgeRange")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Author")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Genre")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Rating")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Reviews")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Summary")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Tags")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Title")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("BookId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            AgeRange = "1-5",
                            Author = "Maurice Sendak",
                            Genre = "Sci-Fi & Fantasy",
                            Rating = "5",
                            Reviews = "This book is amazing!",
                            Summary = "Max sets sail to an island inhabited by Wild Things, who name him king.",
                            Tags = "multi-cultural",
                            Title = "Where The Wild Things Are"
                        },
                        new
                        {
                            BookId = 2,
                            AgeRange = "1-5",
                            Author = "Ezra Jack Keats",
                            Genre = "Picture",
                            Rating = "5",
                            Reviews = "This book is amazing!",
                            Summary = "Peter takes a walk in his snowsuit through New York capturing magic and wonder.",
                            Tags = "multi-cultural",
                            Title = "The Snowy Day"
                        },
                        new
                        {
                            BookId = 3,
                            AgeRange = "Baby-3",
                            Author = "Margaret Wise Brown",
                            Genre = "Picture",
                            Rating = "5",
                            Reviews = "This book is amazing!",
                            Summary = "A little bunny tucked away in bed, says goodnight to all of his favorite things.",
                            Tags = "multi-cultural",
                            Title = "Goodnight Moon"
                        },
                        new
                        {
                            BookId = 4,
                            AgeRange = "5-9",
                            Author = "Shel Silverstein",
                            Genre = "Literature & Fiction",
                            Rating = "5",
                            Reviews = "This book is amazing!",
                            Summary = "Collection of loopy and imaginative poems and drawings, loved by generations.",
                            Tags = "multi-cultural",
                            Title = "Where the Sidewalk Ends"
                        },
                        new
                        {
                            BookId = 5,
                            AgeRange = "15-17",
                            Author = "Stephen King",
                            Genre = "Adventure, Scary",
                            Rating = "4",
                            Reviews = "There is no greater fear than that of losing a child. Stephen King explores the deepest depths of grief and the lengths a father is willing to go through in order to undo the mysterious power of what's beyond the Pet Sematary.",
                            Summary = "When Dr. Louis Creed takes a new job and moves his family to the idyllic, rural town of Ludlow, Maine, this new beginning seems too good to be true.",
                            Tags = "fantasy, supernatural",
                            Title = "Pet Cemetary"
                        },
                        new
                        {
                            BookId = 6,
                            AgeRange = "12-17",
                            Author = "Stephanie Meyer",
                            Genre = "romance, fantasy",
                            Rating = "3.5",
                            Reviews = "I'm team Edward",
                            Summary = "Vampires, warewolves, and high school",
                            Tags = "action, young adult",
                            Title = "Twilight"
                        },
                        new
                        {
                            BookId = 7,
                            AgeRange = "2-8",
                            Author = "Shel Silverstein",
                            Genre = "Bedtime, classics",
                            Rating = "5",
                            Reviews = "Classic",
                            Summary = "Once there was a tree...and she loved a little boy.",
                            Tags = "nature",
                            Title = "The Giving Tree"
                        },
                        new
                        {
                            BookId = 8,
                            AgeRange = "2-5",
                            Author = "Eric Carle",
                            Genre = "Adventure",
                            Rating = "5",
                            Reviews = "This book is amazing!",
                            Summary = "Featuring interactive die-cut pages, this board book edition is the perfect size for little hands and great for teaching counting and days of the week.",
                            Tags = "nature, science",
                            Title = "The Very Hungry Caterpillar"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
